version: 2
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: ./installDeps.sh
      - run:
          name: "Update All"
          command: ./updateAll.sh
      - run:
          name: "Build All"
          command: ./buildAll.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
